### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by SayedSadat** [libetl/curl#11] opened 2018-05-26 19:41 UTC
after compile my project to jar persian characters not show 
see this photo 

https://ibb.co/ktEc38

**Comment by libetl** [comment] 2018-05-27 14:03
I have written three extra unit tests to cover the encoding parsing :

```java
    @Test
    public void theSkyIsBlueInIvritWithTheWrongEncoding() throws IOException {
        HttpResponse response = this.curl("-k -E src/test/resources/clients/libe/libe.pem https://localhost:%d/public/  -H 'Content-Type: text/plain; charset=ISO-8859-1' -d \"השמים כחולים\"");
        Assertions.assertThat(IOUtils.toString(response.getEntity().getContent(), "utf-8")).contains("'????? ??????'");
    }

    @Test
    public void theSkyIsBlueInIvritWithoutEncoding() throws IOException {
        HttpResponse response = this.curl("-k -E src/test/resources/clients/libe/libe.pem https://localhost:%d/public/  -d \"השמים כחולים\"");
        Assertions.assertThat(IOUtils.toString(response.getEntity().getContent(), "utf-8")).contains("'השמים כחולים'");
    }

    @Test
    public void theSkyIsBlueInIvritWithUTF8Encoding() throws IOException {
        HttpResponse response = this.curl("-k -E src/test/resources/clients/libe/libe.pem https://localhost:%d/public/  -H 'Content-Type: text/plain; charset=UTF-8'  -d \"השמים כחולים\"");
        Assertions.assertThat(IOUtils.toString(response.getEntity().getContent(), "utf-8")).contains("'השמים כחולים'");
    }
```

It can now encode a payload using the correct encoding from the Content-Type header.

**Comment by libetl** [comment] 2018-05-27 14:07
will be part of 0.0.17

**Comment by libetl** [comment] 2018-05-27 14:10
0.0.17 is currently staging, should be shipped in a couple of hours.

**Comment by SayedSadat** [comment] 2018-05-27 15:58
in version 0.0.17 Still has the problem :(

**Comment by SayedSadat** [comment] 2018-05-27 16:00
you can use this link for test
https://api.bot-dev.org/danestani/

**Comment by libetl** [comment] 2018-05-27 16:05
Ok, thanks, you mean read data, and not post data.

**Comment by SayedSadat** [comment] 2018-05-27 16:20
Yes

**Comment by SayedSadat** [comment] 2018-05-27 16:32
it work for me in Intellij
but when i compile to jar file not work !
other persian chars show but when i use curl it change text to this
`Ø¢ÛŒØ§ Ù…ÛŒØ¯Ø§Ù†Ø³ØªÛŒØ¯ ØªÙ…Ø§Ù…ÛŒ Ù¾Ø³ØªØ§Ù†Ø¯Ø§Ø±Ø§Ù† Ø¨Ù‡ Ø§Ø³ØªØ«Ù†Ø§ÛŒ Ø§Ù†Ø³Ø§Ù† Ùˆ Ù…ÛŒÙ…ÙˆÙ† Ú©ÙˆØ± Ø±Ù†Ú¯ Ù…ÛŒØ¨Ø§Ø´Ù†Ø¯ØŸ`

**Comment by SayedSadat** [comment] 2018-05-27 16:40
and only persian chars not show 
i dont have problem with English

**Comment by libetl** [comment] 2018-05-27 16:59
Ok. I will give it a try later.

**Comment by libetl** [comment] 2018-05-28 20:41
I was able to test that issue : 
![image](https://user-images.githubusercontent.com/1233790/40628568-11189a1a-62c6-11e8-8922-bd23b6e8db1d.png)

Unfortunately it does not seem to be related to the lib itself, because the problem is caused by a bad display of the text.

When opened in a text editor, I can see that :
![image](https://user-images.githubusercontent.com/1233790/40628667-a1a7bc8c-62c6-11e8-8528-04cc549b5a42.png)
The characters are not lost when saved in a new file.

Then,
- Are there additional steps after retrieving the output ? Please check that you always read the input streams using the UTF-8 encoding, and that you always get the bytes from the string with the UTF-8 encoding too.
- You will have to check your `<meta charset="UTF-8">` if you are using the lib from a webapp,
- or you will have to debug your android app if you are trying to display the text inside a TextInput. Is it correctly rendered from the activity / fragment (use the intelliJ debugger) ?

Sorry I don't have a clue.

**Closed** 2018-06-01 21:13 UTC
